 # only build develop, master & travis branch
 # automatically publish to Playstore Alpha & Appstore Testflight after master build completes
 branches:
  only:
    - master
    - develop
    - travis
before_install:
  - nvm install 8.5.0
  # apply production configuration
  - openssl aes-256-cbc -K $encrypted_178f17f19164_key -iv $encrypted_178f17f19164_iv -in production.zip.enc -out production.zip -d
  - unzip -o production.zip
install: yarn
jobs:
  include:
    - stage: Lint & Test
      language: node_js
      node_js: 8.5.0
      script: yarn job production &&
        yarn lint &&
        yarn test
    - stage: Build iOS
      language: node_js
      node_js: 8.5.0
      os: osx
      osx_image: xcode10.2
      before_script:
        - bundle install
        - cd ios && pod install --repo-update && cd ..
      script: yarn job production &&
        yarn ios:build
    - stage: Release iOS to Testflight
      if: branch = master OR branch = travis
      language: node_js
      node_js: 8.5.0
      os: osx
      osx_image: xcode10.2
      before_script:
        - bundle install
        - cd ios && pod install --repo-update && cd ..
      script:
        # itms is needed, otherwise altool will not work correctly
        yarn job production &&
        yarn ios:build &&
        ln -s "/Applications/Xcode.app/Contents/Applications/Application Loader.app/Contents/Frameworks/ITunesSoftwareService.framework/Support/altool" /usr/local/bin/altool &&
        ln -s "/Applications/Xcode.app/Contents/Applications/Application Loader.app/Contents/itms" /usr/local/bin/itms &&
        altool --upload-app -f "mobile.ipa" -u $PILOT_USERNAME -p $FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD
    - stage: Build Android
      language: android
      jdk: oraclejdk8
      dist: trusty
      android:
        components:
          - tools
          - platform-tools
          - build-tools-28.0.3
          - android-28
          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository
      before_script:
        - gem install bundler
        - bundle install
        # https://stackoverflow.com/questions/54273412/failed-to-install-the-following-android-sdk-packages-as-some-licences-have-not-b
        - mkdir "$ANDROID_HOME/licenses" || true
        - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"
        # https://github.com/wix/react-native-interactable/issues/146
        - cd node_modules/react-native-interactable
        - rm -rf \{ios\,android\} && rm -rf android && rm -rf ios
        - ln -s lib/android . && ln -s lib/ios .
        - cd ../..
      script: yarn job production &&
        yarn job update-version &&
        yarn android:build
    - stage: Release Android to Alpha
      if: branch = master OR branch = travis
      language: android
      jdk: oraclejdk8
      dist: trusty
      android:
        components:
          - tools
          - platform-tools
          - build-tools-28.0.3
          - android-28
          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository
      before_script:
        - gem install bundler
        - bundle install
        # https://stackoverflow.com/questions/54273412/failed-to-install-the-following-android-sdk-packages-as-some-licences-have-not-b
        - mkdir "$ANDROID_HOME/licenses" || true
        - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"
        # https://github.com/wix/react-native-interactable/issues/146
        - cd node_modules/react-native-interactable
        - rm -rf \{ios\,android\} && rm -rf android && rm -rf ios
        - ln -s lib/android . && ln -s lib/ios .
        - cd ../..
      script: yarn job production &&
        yarn job update-version &&
        yarn android:alpha
